"""add_decision_trees_table

Revision ID: e572803515db
Revises: 47d940edfcfe
Create Date: 2025-10-03 06:00:05.184678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e572803515db'
down_revision = '47d940edfcfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tree_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_trees_id'), 'decision_trees', ['id'], unique=False)
    op.create_index(op.f('ix_decision_trees_service_name'), 'decision_trees', ['service_name'], unique=True)
    op.alter_column('audit_logs', 'quote_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.add_column('enquiries', sa.Column('service_tree_id', sa.Integer(), nullable=True))
    op.alter_column('enquiries', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('enquiries', 'initial_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.create_foreign_key(None, 'enquiries', 'decision_trees', ['service_tree_id'], ['id'])
    op.alter_column('enquiry_messages', 'enquiry_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('enquiry_messages', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('knowledge_chunks', 'document_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('knowledge_chunks', 'chunk_index',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('knowledge_chunks', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_column('knowledge_chunks', 'location')
    op.drop_column('knowledge_chunks', 'page_number')
    op.drop_column('knowledge_chunks', 'source_reference')
    op.alter_column('quotes', 'enquiry_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('quotes', 'item_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('quotes', 'base_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('quotes', 'total_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('CUSTOMER', 'ADMIN', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('ADMIN', 'CUSTOMER', name='userrole'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'CUSTOMER', name='userrole'),
               type_=mysql.ENUM('CUSTOMER', 'ADMIN', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('quotes', 'total_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('quotes', 'base_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('quotes', 'item_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.alter_column('quotes', 'enquiry_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('knowledge_chunks', sa.Column('source_reference', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('page_number', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('knowledge_chunks', sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.alter_column('knowledge_chunks', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('knowledge_chunks', 'chunk_index',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('knowledge_chunks', 'document_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('enquiry_messages', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('enquiry_messages', 'enquiry_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.alter_column('enquiries', 'initial_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('enquiries', 'customer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('enquiries', 'service_tree_id')
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('audit_logs', 'quote_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_decision_trees_service_name'), table_name='decision_trees')
    op.drop_index(op.f('ix_decision_trees_id'), table_name='decision_trees')
    op.drop_table('decision_trees')
    # ### end Alembic commands ###
